@ApiGateway_HostAddress = https://localhost:7080
@userId = 1

### Gateway info
GET {{ApiGateway_HostAddress}}/
Accept: application/json

### Get all products
GET {{ApiGateway_HostAddress}}/products?
    phrase=&
    page=1&
    pageSize=10
Accept: application/json

### Create product A
POST {{ApiGateway_HostAddress}}/products
Content-Type: application/json

{
  "name": "Product A",
  "price": 10.00,
  "description": "Description of product A"
}

### Create product B
POST {{ApiGateway_HostAddress}}/products
Content-Type: application/json

{
  "name": "Product B",
  "price": 20.00,
  "description": "Description of product B"
}

### Get product by ID
GET {{ApiGateway_HostAddress}}/products/1
Accept: application/json

### Update product by ID
PUT {{ApiGateway_HostAddress}}/products/1
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 29.99,
  "description": "Updated description"
}

### Delete product by ID
DELETE {{ApiGateway_HostAddress}}/products/1

### Get user cart (lazy-created if empty)
GET {{ApiGateway_HostAddress}}/cart/{{userId}}
Accept: application/json

### Add item to user cart
POST {{ApiGateway_HostAddress}}/cart/{{userId}}/items
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}

### Remove item from user cart
DELETE {{ApiGateway_HostAddress}}/cart/{{userId}}/items/1

### Clear user cart
DELETE {{ApiGateway_HostAddress}}/cart/{{userId}}
